"use client";

import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

export type Language = "en" | "fa";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const translations = {

    fa: {
    home: "خانه",
    about: "منو",
    services: "تماس با ما",
    login1: "اسنپ فود",
    signup: "کد تخفیف",
    language: "زبان",
    getStarted: "ثبت سفارش",
    companyName: "High end",
    location: "موقعیت",
    address: "تهرانپارس غربی، بلوار آیت الله خوشوقت، رحیمی طاری، فست فود های اند",
    address1: "آدرس",
    postalCode: "کد پستی: ۱۲۳۴۵",
    phone: "021-77741981",
    phone2: "۰۲۱۱۲۳۴۵۶۷۸",
    contactUs: "تماس با ما",
    sendMessage: "ارسال پیام",
    support: "مرکز پشتیبانی",
    allRightsReserved: "تمامی حقوق محفوظ است.",
    privacy: "حریم خصوصی",
    terms: "شرایط خدمات",
    ourMenu: "منوی ما",
orderNow:"سفارش دهید",
   backToMenu:"بازگشت",
    // Default items
    deliciousAndFresh: "مواد تازه و خوشمزه",
    chefsSpecialRecommendation: "پیشنهاد ویژه سرآشپز",
    premiumQualityIngredients: "مواد با کیفیت درجه یک",
    popularChoiceAmongCustomers: "انتخاب محبوب مشتریان",
    traditionalRecipeWithModernTwist: "دستور سنتی با لمس مدرن",
    lightAndHealthyOption: "گزینه سبک و سالم",
viewCart:"مشاهده سبد خرید",
addCustomer: "افزودن مشتری",
editCustomer: "ویرایش مشتری",
customerCreated: "مشتری با موفقیت ایجاد شد!",
customerUpdated: "مشتری با موفقیت بروزرسانی شد!",
customerDeleted: "مشتری با موفقیت حذف شد!",
errorCreatingCustomer: "خطا در ایجاد مشتری",
errorUpdatingCustomer: "خطا در بروزرسانی مشتری",
errorDeletingCustomer: "خطا در حذف مشتری",
confirmDeleteCustomer: "آیا مطمئن هستید که می‌خواهید این مشتری را حذف کنید؟",

    // Additional Default
    seasonalSpecialty: "تخصص فصلی با مواد تازه",
    chefRecommended: "غذای امضا پیشنهادی سرآشپز",
    cart: "سبد خرید",
    shoppingCart: "سبد خرید",
    cartEmpty: "سبد خرید شما خالی است",
    total: "مجموع",
    clearCart: "پاک کردن سبد",
    checkout: "پرداخت",
    findUs: "ما را پیدا کنید و در تماس باشید",
    email: "ایمیل",
    followUs: "ما را دنبال کنید",
    // Form/Survey translations
    customerSurvey: "نظرسنجی مشتریان",
    surveyDescription: "به ما کمک کنید تا تجربه غذاخوری شما را بهبود دهیم",
    surveySubmitted: "از بازخورد شما متشکریم!",
    submitError: "خطا در ارسال نظرسنجی. لطفاً دوباره تلاش کنید.",

    // Form steps
    personalInfo: "اطلاعات شخصی",
    visitInfo: "اطلاعات بازدید",
    ratings: "امتیاز دهی به تجربه شما",
    feedback: "بازخورد شما",
    preferences: "ترجیحات و بازاریابی",

    // Step labels
    personal: "شخصی",
    visit: "بازدید",

    // Form fields
    name: "نام",
    email1: "ایمیل",
    phone1: "تلفن",
    ageGroup: "گروه سنی",
    enterName: "نام خود را وارد کنید",
    enterEmail: "ایمیل خود را وارد کنید",
    enterPhone: "شماره تلفن خود را وارد کنید",
    selectAge: "گروه سنی را انتخاب کنید",
    over56: "۵۶+",

    // Visit information
    visitFrequency: "چند وقت یکبار از ما بازدید می‌کنید؟",
    firstTime: "اولین بار",
    weekly: "هفتگی",
    monthly: "ماهانه",
    occasionally: "گاهی اوقات",
    rarely: "به ندرت",
    lastVisit: "آخرین بازدید شما کی بود؟",
    partySize: "تعداد افراد",
    selectPartySize: "تعداد افراد را انتخاب کنید",
    sevenPlus: "۷+",
    occasion: "مناسبت",
    selectOccasion: "مناسبت را انتخاب کنید",
    casual: "غذاخوری معمولی",
    business: "جلسه کاری",
    celebration: "جشن",
    date: "تاریخ",
    family: "گردهمایی خانوادگی",

    // Ratings
    foodQuality: "کیفیت غذا",
    serviceQuality: "کیفیت سرویس",
    atmosphere: "فضا",
    valueForMoney: "ارزش در برابر پول",

    // Feedback
    mostLiked: "بیشترین چیزی که دوست داشتید چه بود؟",
    describeMostLiked: "بگویید بیشترین لذت را از چه چیزی در تجربه‌تان بردید",
    improvements: "چه چیزی را می‌توانیم بهبود دهیم؟",
    describeImprovements: "پیشنهادات خود برای بهبود را با ما در میان بگذارید",
    recommendation: "چقدر احتمال دارد ما را توصیه کنید؟",
    notLikely: "احتمال کم",
    veryLikely: "احتمال زیاد",
    additionalComments: "نظرات اضافی",
    shareThoughts: "هر نظر یا پیشنهاد اضافی را با ما در میان بگذارید",

    // Preferences
    favoriteItems: "آیتم‌های مورد علاقه منو",
    dietaryRestrictions: "محدودیت‌های غذایی",
    vegetarian: "گیاهخوار",
    vegan: "وگان",
    glutenFree: "بدون گلوتن",
    dairyFree: "بدون لبنیات",
    nutFree: "بدون آجیل",
    halal: "حلال",
    kosher: "کوشر",
    none: "هیچ",
    preferredTime: "زمان ترجیحی غذاخوری",
    selectTime: "زمان ترجیحی را انتخاب کنید",
    breakfast: "صبحانه (۷-۱۱ صبح)",
    lunch: "ناهار (۱۱ صبح-۳ بعدازظهر)",
    dinner: "شام (۵-۱۰ شب)",
    lateNight: "شب دیر (۱۰ شب+)",

    // Marketing
    hearAboutUs: "چطور از ما باخبر شدید؟",
    socialMedia: "شبکه‌های اجتماعی",
    friendsFamily: "دوستان/خانواده",
    onlineSearch: "جستجوی آنلاین",
    advertisement: "تبلیغات",
    walkBy: "از کنار رد شدم",
    other: "سایر",
    subscribeNewsletter: "عضویت در خبرنامه",
    receivePromotions: "دریافت پیشنهادات تبلیغاتی",

    // Form actions
    previous: "قبلی",
    next: "بعدی",
    submitSurvey: "ارسال نظرسنجی",
    submitting: "در حال ارسال...",

    // Validation messages
    nameRequired: "نام الزامی است",
    emailRequired: "ایمیل الزامی است",
    emailInvalid: "ایمیل نامعتبر است",
    visitFrequencyRequired: "تعدد بازدید الزامی است",
    ratingRequired: "امتیاز الزامی است",
    feedbackRequired: "این فیلد الزامی است",
    recommendationRequired: "امتیاز توصیه الزامی است",
    // Location & Contact translations
    getDirections: "مسیریابی",
    openInGoogleMaps: "گوگل مپ",
    openInOSM: "نقشه آزاد",
    coordinates: "مختصات",
    copyCoordinates: "برای کپی مختصات کلیک کنید",
    businessHours: "ساعات کاری",
    monday: "دوشنبه",
    tuesday: "سه‌شنبه",
    wednesday: "چهارشنبه",
    thursday: "پنج‌شنبه",
    friday: "جمعه",
    saturday: "شنبه",
    sunday: "یکشنبه",
    loading: "در حال بارگذاری...",

    // Form translations (additional)
    surveySubmittedDesc: "پاسخ شما ثبت شد و به بهبود خدمات ما کمک خواهد کرد.",
    submitAnother: "ارسال پاسخ دیگر",
    enterFavoriteItems: "آیتم‌های مورد علاقه خود را وارد کنید",
    selectOption: "یک گزینه انتخاب کنید",

     // Size labels
    small: "کوچک",
    large: "بزرگ",
    unavailable: "اتمام موجودی",

orderSummary: "خلاصه سفارش",
discountCode: "کد تخفیف",
enterDiscountCode: "کد تخفیف را وارد کنید",
apply: "اعمال",
validating: "در حال بررسی...",
remove: "حذف",
discount: "تخفیف",
subtotal: "جمع جزء",
proceedToCheckout: "ادامه خرید",
customerInformation: "اطلاعات مشتری",
back: "بازگشت",
enterAddress: "آدرس کامل خود را وارد کنید",
enterNotes: "توضیحات خاص (اختیاری)",
notes: "یادداشت",
phoneRequired: "شماره تلفن الزامی است",
phoneInvalid: "شماره تلفن نامعتبر است",
addressRequired: "آدرس الزامی است",
processing: "در حال پردازش...",
proceedToPayment: "ادامه به پرداخت",
payment: "پرداخت",
orderNumber: "شماره سفارش",
amountToPay: "مبلغ قابل پرداخت",
paymentInstructions: "روی دکمه زیر کلیک کنید تا به درگاه پرداخت منتقل شوید",
payNow: "پرداخت کنید",
paymentInfo: "شما به صفحه پرداخت امن منتقل خواهید شد. پس از پرداخت، تأییدیه را خواهید دید.",
paymentSuccessful: "پرداخت موفق!",
orderConfirmed: "سفارش شما تأیید شد و به زودی پردازش خواهد شد.",
placeNewOrder: "ثبت سفارش جدید",
paymentFailed: "پرداخت ناموفق",
paymentFailedMessage: "مشکلی در پردازش پرداخت شما وجود داشت. لطفاً دوباره تلاش کنید.",
retryPayment: "تلاش مجدد پرداخت",
startOver: "شروع مجدد",
errorValidatingCoupon: "خطا در بررسی کد تخفیف",
errorCreatingOrder: "خطا در ایجاد سفارش",
retry: "تلاش مجدد",
  
  // Employee Login
  employeeLogin: "ورود کارمند",
  loginDescription: "به داشبورد کارمندی خود دسترسی پیدا کنید",
  password: "رمز عبور",
  enterPassword: "رمز عبور خود را وارد کنید",
  passwordRequired: "رمز عبور الزامی است",
  passwordTooShort: "رمز عبور باید حداقل ۶ کاراکتر باشد",
  login: "ورود",
  loggingIn: "در حال ورود...",
  loginError: "ورود ناموفق. لطفاً دوباره تلاش کنید.",
  forgotPassword: "رمز عبور خود را فراموش کرده‌اید؟",
  contactAdmin: "با مدیر تماس بگیرید",
  
  // Dashboard
  welcomeBack: "خوش آمدید",
  role: "نقش",
  logout: "خروج",
  quickActions: "اقدامات سریع",
  viewReports: "مشاهده گزارش‌ها",
  manageSurveys: "مدیریت نظرسنجی‌ها",
  customerData: "اطلاعات مشتریان",
  adminPanel: "پنل مدیریت",
overview: "نمای کلی",
menuManagement: "مدیریت منو",
orders: "سفارشات",
surveyResults: "نتایج نظرسنجی",
analytics: "تحلیلات",
totalOrders: "کل سفارشات",
pendingOrders: "سفارشات در انتظار",
surveyResponses: "پاسخ‌های نظرسنجی",
avgRating: "میانگین امتیاز",
recentOrders: "سفارشات اخیر",
addNewItem: "افزودن آیتم جدید",
available: "موجود",
edit: "ویرایش",
disable: "غیرفعال",
enable: "فعال",
editItem: "ویرایش آیتم",
itemName: "نام آیتم",
originalPrice: "قیمت اصلی",
smallPrice: "قیمت کوچک",
largePrice: "قیمت بزرگ",
imageUrl: "آدرس تصویر",
isDiscounted: "تخفیف دارد",
isAvailable: "موجود است",
cancel: "لغو",
add: "افزودن",
save: "ذخیره",
orderManagement: "مدیریت سفارشات",
allOrders: "همه سفارشات",
pending: "در انتظار",
preparing: "در حال آماده‌سازی",
ready: "آماده",
completed: "تکمیل شده",
cancelled: "لغو شده",
totalResponses: "کل پاسخ‌ها",
avgFoodRating: "میانگین امتیاز غذا",
avgServiceRating: "میانگین امتیاز سرویس",
today: "امروز",
thisWeek: "این هفته",
thisMonth: "این ماه",
thisYear: "امسال",
salesOverview: "نمای کلی فروش",
totalRevenue: "کل درآمد",
avgOrderValue: "میانگین ارزش سفارش",
completedOrders: "سفارشات تکمیل شده",
customerSatisfaction: "رضایت مشتری",
recommendationRate: "نرخ توصیه",
orderStatus: "توزیع وضعیت سفارشات",
topFeedback: "بازخوردهای اخیر",
// Dashboard translations
dashboard: "داشبورد",
surveys: "نظرسنجی‌ها",
menu: "منو",
coupons: "کوپن‌ها",

// Orders Management
ordersManagement: "مدیریت سفارشات",
customer: "مشتری",
status: "وضعیت",
actions: "عملیات",
confirmed: "تأیید شده",
delivered: "تحویل داده شده",
viewDetails: "مشاهده جزئیات",

// Survey Results
avgFoodQuality: "میانگین کیفیت غذا",
contact: "تماس",
visitFreq: "تکرار بازدید",
surveyDetails: "جزئیات نظرسنجی",
customerInfo: "اطلاعات مشتری",
age: "سن",
additional: "اضافی",
newsletter: "خبرنامه",
promotions: "تبلیغات",
submittedAt: "ارسال شده در",
close: "بستن",

// Menu Management
allCategories: "همه دسته‌بندی‌ها",
image: "تصویر",
category: "دسته‌بندی",
description: "توضیحات",
price: "قیمت",
discounted: "تخفیف‌دار",
yes: "بله",
no: "خیر",
editMenuItem: "ویرایش آیتم منو",
hasSizes: "اندازه‌های مختلف دارد",
priceSmall: "قیمت (کوچک)",
priceLarge: "قیمت (بزرگ)",
originalPrices: "قیمت‌های اصلی",
smallSizeDiscounted: "اندازه کوچک تخفیف‌دار",
largeSizeDiscounted: "اندازه بزرگ تخفیف‌دار",
originalPriceSmall: "قیمت اصلی (کوچک)",
originalPriceLarge: "قیمت اصلی (بزرگ)",
saving: "در حال ذخیره...",
itemUpdated: "آیتم منو با موفقیت به‌روزرسانی شد!",
updateError: "خطا در به‌روزرسانی آیتم منو",

// Coupon Management
couponManagement: "مدیریت کوپن‌ها",
addCoupon: "افزودن کوپن",
code: "کد",
minOrder: "حداقل سفارش",
maxDiscount: "حداکثر تخفیف",
usage: "استفاده",
expires: "انقضا",
active: "فعال",
inactive: "غیرفعال",
delete: "حذف",
editCoupon: "ویرایش کوپن",
couponCode: "کد کوپن",
discountType: "نوع تخفیف",
percentage: "درصد (%)",
fixedAmount: "مقدار ثابت (T)",
discountPercentage: "درصد تخفیف",
discountAmount: "مقدار تخفیف",
minOrderAmount: "حداقل مقدار سفارش",
maxDiscountAmount: "حداکثر مقدار تخفیف",
usageLimit: "محدودیت استفاده",
validUntil: "معتبر تا",
update: "به‌روزرسانی",
create: "ایجاد",
sizeConfiguration: "پیکربندی اندازه",
priceConfiguration: "پیکربندی قیمت",
smallSize: "اندازه کوچک",
largeSize: "اندازه بزرگ",
availability: "در دسترس بودن",
// Add these to your Persian translations
paidOrders: "سفارشات پرداخت شده",
paymentStatus: "وضعیت پرداخت",
paid: "پرداخت شده",
failed: "ناموفق",
refunded: "بازپرداخت شده",
viewPayment: "مشاهده پرداخت",
orderDetails: "جزئیات سفارش",
orderInfo: "اطلاعات سفارش",
orderDate: "تاریخ سفارش",
paymentRef: "مرجع پرداخت",
orderItems: "آیتم‌های سفارش",
items: "آیتم‌ها",
customers: "مشتریان",
customerManagement: "مدیریت مشتریان",
totalCustomers: "کل مشتریان",
withEmail: "با ایمیل",
recentCustomers: "این ماه",
firstOrder: "اولین سفارش",
lastUpdated: "آخرین بروزرسانی",
customerDetails: "جزئیات مشتری",
noEmail: "بدون ایمیل",
timeline: "جدول زمانی",
firstSeen: "اولین بازدید",
customerSince: "مشتری از",
daysAgo: "روز پیش",
call: "تماس با مشتری",
trackYourOrder: "پیگیری سفارش شما",
orderReceived: "دریافت و تایید سفارش",
preparingOrder: "آماده‌سازی سفارش شما",
readyForDelivery: "آماده و تحویل به پیک",
orderReceivedDesc: "رستوران سفارش شما را دریافت و تایید کرده است",
preparingOrderDesc: "آشپزهای ما در حال آماده‌سازی غذای خوشمزه شما هستند",
readyForDeliveryDesc: "سفارش آماده و به پیک تحویل داده شده است",
deliveredDesc: "سفارش شما تحویل داده شد. از غذایتان لذت ببرید!",
inProgress: "در حال انجام...",
awaitingDelivery: "در انتظار تحویل",
needHelp: "کمک نیاز دارید؟",
contactDescription: "اگر سوالی درباره سفارشتان دارید، با ما تماس بگیرید:",
supportHours: "پشتیبانی",
},

en: {
  home: "Home",
  about: "Menu",
  services: "Contact Us",
  login1: "Snap Food",
  signup: "Discount Code",
  language: "Language",
  getStarted: "Place Order",
  companyName: "High end",
  location: "Location",
  address: "Tehranpars Gharbi, Ayatollah Khoshvaght Boulevard, Rahimi Tari, HighEnd Fast Food",
  address1: "Address",
  postalCode: "Postal Code: 12345",
  phone: "021-77741981",
  phone2: "02112345678",
  contactUs: "Contact Us",
  sendMessage: "Send Message",
  support: "Support Center",
  allRightsReserved: "All rights reserved.",
  privacy: "Privacy Policy",
  terms: "Terms of Service",
  ourMenu: "Our Menu",
  orderNow: "Order Now",
  backToMenu: "Back to Menu",
  
  // Default items
  deliciousAndFresh: "Fresh and delicious ingredients",
  chefsSpecialRecommendation: "Chef's special recommendation",
  premiumQualityIngredients: "Premium quality ingredients",
  popularChoiceAmongCustomers: "Popular choice among customers",
  traditionalRecipeWithModernTwist: "Traditional recipe with modern twist",
  lightAndHealthyOption: "Light and healthy option",
viewCart:"View Cart",
addCustomer: "Add Customer",
editCustomer: "Edit Customer",
customerCreated: "Customer created successfully!",
customerUpdated: "Customer updated successfully!",
customerDeleted: "Customer deleted successfully!",
errorCreatingCustomer: "Error creating customer",
errorUpdatingCustomer: "Error updating customer",
errorDeletingCustomer: "Error deleting customer",
confirmDeleteCustomer: "Are you sure you want to delete this customer?",

  // Additional Default
  seasonalSpecialty: "Seasonal specialty with fresh ingredients",
  chefRecommended: "Chef's signature recommended dish",
  cart: "Cart",
  shoppingCart: "Shopping Cart",
  cartEmpty: "Your cart is empty",
  total: "Total",
  clearCart: "Clear Cart",
  checkout: "Checkout",
  findUs: "Find us and stay in touch",
  email: "Email",
  followUs: "Follow Us",
  
  // Form/Survey translations
  customerSurvey: "Customer Survey",
  surveyDescription: "Help us improve your dining experience",
  surveySubmitted: "Thank you for your feedback!",
  submitError: "Error submitting survey. Please try again.",

  // Form steps
  personalInfo: "Personal Information",
  visitInfo: "Visit Information",
  ratings: "Rate Your Experience",
  feedback: "Your Feedback",
  preferences: "Preferences and Marketing",

  // Step labels
  personal: "Personal",
  visit: "Visit",

  // Form fields
  name: "Name",
  email1: "Email",
  phone1: "Phone",
  ageGroup: "Age Group",
  enterName: "Enter your name",
  enterEmail: "Enter your email",
  enterPhone: "Enter your phone number",
  selectAge: "Select age group",
  over56: "56+",

  // Visit information
  visitFrequency: "How often do you visit us?",
  firstTime: "First time",
  weekly: "Weekly",
  monthly: "Monthly",
  occasionally: "Occasionally",
  rarely: "Rarely",
  lastVisit: "When was your last visit?",
  partySize: "Party size",
  selectPartySize: "Select party size",
  sevenPlus: "7+",
  occasion: "Occasion",
  selectOccasion: "Select occasion",
  casual: "Casual dining",
  business: "Business meeting",
  celebration: "Celebration",
  date: "Date night",
  family: "Family gathering",

  // Ratings
  foodQuality: "Food Quality",
  serviceQuality: "Service Quality",
  atmosphere: "Atmosphere",
  valueForMoney: "Value for Money",

  // Feedback
  mostLiked: "What did you like most?",
  describeMostLiked: "Tell us what you enjoyed most about your experience",
  improvements: "What could we improve?",
  describeImprovements: "Share your suggestions for improvement",
  recommendation: "How likely are you to recommend us?",
  notLikely: "Not likely",
  veryLikely: "Very likely",
  additionalComments: "Additional Comments",
  shareThoughts: "Share any additional thoughts or comments",

  // Preferences
  favoriteItems: "Favorite menu items",
  dietaryRestrictions: "Dietary restrictions",
  vegetarian: "Vegetarian",
  vegan: "Vegan",
  glutenFree: "Gluten-free",
  dairyFree: "Dairy-free",
  nutFree: "Nut-free",
  halal: "Halal",
  kosher: "Kosher",
  none: "None",
  preferredTime: "Preferred dining time",
  selectTime: "Select preferred time",
  breakfast: "Breakfast (7-11 AM)",
  lunch: "Lunch (11 AM-3 PM)",
  dinner: "Dinner (5-10 PM)",
  lateNight: "Late night (10 PM+)",

  // Marketing
  hearAboutUs: "How did you hear about us?",
  socialMedia: "Social media",
  friendsFamily: "Friends/Family",
  onlineSearch: "Online search",
  advertisement: "Advertisement",
  walkBy: "Walked by",
  other: "Other",
  subscribeNewsletter: "Subscribe to newsletter",
  receivePromotions: "Receive promotional offers",

  // Form actions
  previous: "Previous",
  next: "Next",
  submitSurvey: "Submit Survey",
  submitting: "Submitting...",

  // Validation messages
  nameRequired: "Name is required",
  emailRequired: "Email is required",
  emailInvalid: "Email is invalid",
  visitFrequencyRequired: "Visit frequency is required",
  ratingRequired: "Rating is required",
  feedbackRequired: "This field is required",
  recommendationRequired: "Recommendation rating is required",
  
  // Location & Contact translations
  getDirections: "Get Directions",
  openInGoogleMaps: "Open in Google Maps",
  openInOSM: "Open in OpenStreetMap",
  coordinates: "Coordinates",
  copyCoordinates: "Click to copy coordinates",
  businessHours: "Business Hours",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  sunday: "Sunday",
  loading: "Loading...",

  // Form translations (additional)
  surveySubmittedDesc: "Your response has been recorded and will help improve our service.",
  submitAnother: "Submit Another Response",
  enterFavoriteItems: "Enter your favorite items",
  selectOption: "Select an option",

  // Size labels
  small: "Small",
  large: "Large",
  unavailable: "Out of Stock",

  orderSummary: "Order Summary",
  discountCode: "Discount Code",
  enterDiscountCode: "Enter discount code",
  apply: "Apply",
  validating: "Validating...",
  remove: "Remove",
  discount: "Discount",
  subtotal: "Subtotal",
  proceedToCheckout: "Proceed to Checkout",
  customerInformation: "Customer Information",
  back: "Back",
  enterAddress: "Enter your full address",
  enterNotes: "Special instructions (optional)",
  notes: "Notes",
  phoneRequired: "Phone number is required",
  phoneInvalid: "Phone number is invalid",
  addressRequired: "Address is required",
  processing: "Processing...",
  proceedToPayment: "Proceed to Payment",
  payment: "Payment",
  orderNumber: "Order Number",
  amountToPay: "Amount to Pay",
  paymentInstructions: "Click the button below to proceed to payment gateway",
  payNow: "Pay Now",
  paymentInfo: "You will be redirected to a secure payment page. After payment, you will see the confirmation.",
  paymentSuccessful: "Payment Successful!",
  orderConfirmed: "Your order has been confirmed and will be processed shortly.",
  placeNewOrder: "Place New Order",
  paymentFailed: "Payment Failed",
  paymentFailedMessage: "There was an issue processing your payment. Please try again.",
  retryPayment: "Retry Payment",
  startOver: "Start Over",
  errorValidatingCoupon: "Error validating coupon",
  errorCreatingOrder: "Error creating order",
  retry: "Retry",
  
  // Employee Login
  employeeLogin: "Employee Login",
  loginDescription: "Access your employee dashboard",
  password: "Password",
  enterPassword: "Enter your password",
  passwordRequired: "Password is required",
  passwordTooShort: "Password must be at least 6 characters",
  login: "Login",
  loggingIn: "Logging in...",
  loginError: "Login failed. Please try again.",
  forgotPassword: "Forgot your password?",
  contactAdmin: "Contact admin",
  
  // Dashboard
  welcomeBack: "Welcome back",
  role: "Role",
  logout: "Logout",
  quickActions: "Quick Actions",
  viewReports: "View Reports",
  manageSurveys: "Manage Surveys",
  customerData: "Customer Data",
  adminPanel: "Admin Panel",
  overview: "Overview",
  menuManagement: "Menu Management",
  orders: "Orders",
  surveyResults: "Survey Results",
  analytics: "Analytics",
  totalOrders: "Total Orders",
  pendingOrders: "Pending Orders",
  surveyResponses: "Survey Responses",
  avgRating: "Average Rating",
  recentOrders: "Recent Orders",
  addNewItem: "Add New Item",
  available: "Available",
  edit: "Edit",
  disable: "Disable",
  enable: "Enable",
  editItem: "Edit Item",
  itemName: "Item Name",
  originalPrice: "Original Price",
  smallPrice: "Small Price",
  largePrice: "Large Price",
  imageUrl: "Image URL",
  isDiscounted: "Is Discounted",
  isAvailable: "Is Available",
  cancel: "Cancel",
  add: "Add",
  save: "Save",
  orderManagement: "Order Management",
  allOrders: "All Orders",
  pending: "Pending",
  preparing: "Preparing",
  ready: "Ready",
  completed: "Completed",
  cancelled: "Cancelled",
  totalResponses: "Total Responses",
  avgFoodRating: "Average Food Rating",
  avgServiceRating: "Average Service Rating",
  today: "Today",
  thisWeek: "This Week",
  thisMonth: "This Month",
  thisYear: "This Year",
  salesOverview: "Sales Overview",
  totalRevenue: "Total Revenue",
  avgOrderValue: "Average Order Value",
  completedOrders: "Completed Orders",
  customerSatisfaction: "Customer Satisfaction",
  recommendationRate: "Recommendation Rate",
  orderStatus: "Order Status Distribution",
  topFeedback: "Recent Feedback",
  
  // Dashboard translations
  dashboard: "Dashboard",
  surveys: "Surveys",
  menu: "Menu",
  coupons: "Coupons",

  // Orders Management
  ordersManagement: "Orders Management",
  customer: "Customer",
  status: "Status",
  actions: "Actions",
  confirmed: "Confirmed",
  delivered: "Delivered",
  viewDetails: "View Details",

  // Survey Results
  avgFoodQuality: "Average Food Quality",
  contact: "Contact",
  visitFreq: "Visit Frequency",
  surveyDetails: "Survey Details",
  customerInfo: "Customer Information",
  age: "Age",
  additional: "Additional",
  newsletter: "Newsletter",
  promotions: "Promotions",
  submittedAt: "Submitted at",
  close: "Close",

  // Menu Management
  allCategories: "All Categories",
  image: "Image",
  category: "Category",
  description: "Description",
  price: "Price",
  discounted: "Discounted",
  yes: "Yes",
  no: "No",
  editMenuItem: "Edit Menu Item",
  hasSizes: "Has Multiple Sizes",
  priceSmall: "Price (Small)",
  priceLarge: "Price (Large)",
  originalPrices: "Original Prices",
  smallSizeDiscounted: "Small Size Discounted",
  largeSizeDiscounted: "Large Size Discounted",
  originalPriceSmall: "Original Price (Small)",
  originalPriceLarge: "Original Price (Large)",
  saving: "Saving...",
  itemUpdated: "Menu item updated successfully!",
  updateError: "Error updating menu item",

  // Coupon Management
  couponManagement: "Coupon Management",
  addCoupon: "Add Coupon",
  code: "Code",
  minOrder: "Min Order",
  maxDiscount: "Max Discount",
  usage: "Usage",
  expires: "Expires",
  active: "Active",
  inactive: "Inactive",
  delete: "Delete",
  editCoupon: "Edit Coupon",
  couponCode: "Coupon Code",
  discountType: "Discount Type",
  percentage: "Percentage (%)",
  fixedAmount: "Fixed Amount (T)",
  discountPercentage: "Discount Percentage",
  discountAmount: "Discount Amount",
  minOrderAmount: "Minimum Order Amount",
  maxDiscountAmount: "Maximum Discount Amount",
  usageLimit: "Usage Limit",
  validUntil: "Valid Until",
  update: "Update",
  create: "Create",
  sizeConfiguration: "Size Configuration",
  priceConfiguration: "Price Configuration",
  smallSize: "Small Size",
  largeSize: "Large Size",
  availability: "Availability",
  
  // Add these to your English translations
  paidOrders: "Paid Orders",
  paymentStatus: "Payment Status",
  paid: "Paid",
  failed: "Failed",
  refunded: "Refunded",
  viewPayment: "View Payment",
  orderDetails: "Order Details",
  orderInfo: "Order Information",
  orderDate: "Order Date",
  paymentRef: "Payment Reference",
  orderItems: "Order Items",
  items: "Items",
  customers: "Customers",
customerManagement: "Customer Management",
totalCustomers: "Total Customers",
withEmail: "With Email",
recentCustomers: "This Month",
firstOrder: "First Order",
lastUpdated: "Last Updated",
customerDetails: "Customer Details",
noEmail: "No email",
timeline: "Timeline",
firstSeen: "First Seen",
customerSince: "Customer Since",
daysAgo: "days ago",
call: "Call Customer",
trackYourOrder: "Track Your Order",
orderReceived: "Order Received & Approved",
preparingOrder: "Preparing Your Order",
readyForDelivery: "Ready & Handed to Courier",
orderReceivedDesc: "Restaurant has received and approved your order",
preparingOrderDesc: "Our chefs are preparing your delicious meal",
readyForDeliveryDesc: "Order is ready and handed over to delivery courier",
deliveredDesc: "Your order has been delivered. Enjoy your meal!",
inProgress: "In Progress...",
awaitingDelivery: "Awaiting Delivery",
needHelp: "Need Help?",
contactDescription: "If you have any questions about your order, please call us:",
supportHours: "Support",
},


  
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("fa");

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "fa")) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    // Save language to localStorage and update document direction
    localStorage.setItem("language", language);
    document.documentElement.dir = language === "fa" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const isRTL = language === "fa";

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
